# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Action Takers
email: your-email@example.com
description: Actions Takers is a community of civic-minded people who understand the role of public participation in our democracy and use that power to ensure their voices are heard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://actiontakers.co.za" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
logo: /img/logo.png

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed

collections:
  risk-of-eviction:
    output: true
    title: "Risk of eviction"
    description: "A guide on what to do if you are at risk of being evicted"
    category: housing
  access-education:
    output: true
    title: "Access to Education"
    description: "A guide on how to overcome barriers to learning and get your child the education they deserve"
    category: education
  steps:
    output: true